[project]
name = "podcast-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx-whisper>=0.4.3",
    "requests>=2.32.5",
]
